/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE GH_CMD PACKING
package com.example.MAVLINK.gh;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Send a custom command with integer parameters
 */
public class msg_gh_cmd extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_GH_CMD = 21000;
    public static final int MAVLINK_MSG_LENGTH = 34;
    private static final long serialVersionUID = MAVLINK_MSG_ID_GH_CMD;

    
    /**
     * 
     */
    @Description("")
    @Units("")
    public float param1;
    
    /**
     * 
     */
    @Description("")
    @Units("")
    public float param2;
    
    /**
     * 
     */
    @Description("")
    @Units("")
    public float param3;
    
    /**
     * 
     */
    @Description("")
    @Units("")
    public float param4;
    
    /**
     * 
     */
    @Description("")
    @Units("")
    public int param5;
    
    /**
     * 
     */
    @Description("")
    @Units("")
    public int param6;
    
    /**
     * 
     */
    @Description("")
    @Units("")
    public int param7;
    
    /**
     * no gaps in the sequence (0,1,2,3,4).
     */
    @Description("no gaps in the sequence (0,1,2,3,4).")
    @Units("")
    public int seq;
    
    /**
     * 
     */
    @Description("")
    @Units("")
    public int command_id;
    
    /**
     * 
     */
    @Description("")
    @Units("")
    public short target_system;
    
    /**
     * 
     */
    @Description("")
    @Units("")
    public short target_component;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_GH_CMD;

        packet.payload.putFloat(param1);
        packet.payload.putFloat(param2);
        packet.payload.putFloat(param3);
        packet.payload.putFloat(param4);
        packet.payload.putInt(param5);
        packet.payload.putInt(param6);
        packet.payload.putInt(param7);
        packet.payload.putUnsignedShort(seq);
        packet.payload.putUnsignedShort(command_id);
        packet.payload.putUnsignedByte(target_system);
        packet.payload.putUnsignedByte(target_component);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a gh_cmd message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.param1 = payload.getFloat();
        this.param2 = payload.getFloat();
        this.param3 = payload.getFloat();
        this.param4 = payload.getFloat();
        this.param5 = payload.getInt();
        this.param6 = payload.getInt();
        this.param7 = payload.getInt();
        this.seq = payload.getUnsignedShort();
        this.command_id = payload.getUnsignedShort();
        this.target_system = payload.getUnsignedByte();
        this.target_component = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_gh_cmd() {
        this.msgid = MAVLINK_MSG_ID_GH_CMD;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_gh_cmd( float param1, float param2, float param3, float param4, int param5, int param6, int param7, int seq, int command_id, short target_system, short target_component) {
        this.msgid = MAVLINK_MSG_ID_GH_CMD;

        this.param1 = param1;
        this.param2 = param2;
        this.param3 = param3;
        this.param4 = param4;
        this.param5 = param5;
        this.param6 = param6;
        this.param7 = param7;
        this.seq = seq;
        this.command_id = command_id;
        this.target_system = target_system;
        this.target_component = target_component;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_gh_cmd( float param1, float param2, float param3, float param4, int param5, int param6, int param7, int seq, int command_id, short target_system, short target_component, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_GH_CMD;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.param1 = param1;
        this.param2 = param2;
        this.param3 = param3;
        this.param4 = param4;
        this.param5 = param5;
        this.param6 = param6;
        this.param7 = param7;
        this.seq = seq;
        this.command_id = command_id;
        this.target_system = target_system;
        this.target_component = target_component;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_gh_cmd(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_GH_CMD;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                          
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_GH_CMD - sysid:"+sysid+" compid:"+compid+" param1:"+param1+" param2:"+param2+" param3:"+param3+" param4:"+param4+" param5:"+param5+" param6:"+param6+" param7:"+param7+" seq:"+seq+" command_id:"+command_id+" target_system:"+target_system+" target_component:"+target_component+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_GH_CMD";
    }
}
        